language: cpp
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: osx
          osx_image: xcode8
install: ./setup
script:
  - cd ./firmware/HelloWorld/
  - source env.sh
  - make presubmit
after_success:
  - cd ../../
  - gcov-7 --version # debug only
  - g++-7 --version # debug only
  - bash <(curl -s https://codecov.io/bash) -x $(which gcov-7)
